In [4]:
import numpy as np

In [5]:
#Ejercicio 1
np.random.seed(1)
array1 = np.random.random_sample((2,3))
array1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [6]:
np.random.seed(1)
array2 = np.random.random_sample((2,3))
array2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [19]:
#Ejericicio 2:

sol = np.random.uniform(0,10,size = (2,3,5))
sol = np.round(sol, decimals = 0)
sol

valores_unicos_sol = np.unique(sol)
valores_unicos_sol

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
cielo = np.random.binomial(10, 0.3, size = (2,3,5))
cielo

valores_unicos_cielo = np.unique(cielo)
valores_unicos_cielo

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
#Ejercicio 3
interseccion = np.intersect1d(sol,cielo)
print('Intersección de los arrays:',interseccion,'\n') #valores unicos comunes en los dos arrays
union = np.union1d(sol, cielo)
print('La unión de los arrays:',union,'\n')            #Une los valores de los arrays sin duplicados
diferencia_conjunta = np.setdiff1d(sol, cielo)
print('Los valores únicos en sol pero no en cielo:', diferencia_conjunta) #valores únicos que están en sol pero no en cielo
                                                                          #si cambiamos el orden de los arrays saldrán los que
                                                                          #están en cielo pero no en sol.

Intersección de los arrays: [0. 1. 2. 3. 4. 5. 6.] 

La unión de los arrays: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

Los valores únicos no comunes de los arrays: [ 7.  8.  9. 10.]


In [29]:
#Ejercicio 4:
array_1 = np.random.rand(80)
array_1

array_2 = np.random.rand(80)
array_2

array([0.22843752, 0.10253022, 0.74248998, 0.98520391, 0.25337959,
       0.4436461 , 0.67804084, 0.49128817, 0.23321602, 0.04593675,
       0.54744656, 0.09649437, 0.11627475, 0.97571623, 0.40562445,
       0.88637191, 0.06041313, 0.15136477, 0.23586686, 0.4207642 ,
       0.02829581, 0.33663294, 0.20637762, 0.28987521, 0.36860197,
       0.45707317, 0.0240101 , 0.82811755, 0.90252243, 0.83811903,
       0.22944513, 0.36426927, 0.4877371 , 0.40182828, 0.58223021,
       0.48362661, 0.55239384, 0.65931242, 0.47648046, 0.71129948,
       0.7249678 , 0.60616181, 0.45143285, 0.09318096, 0.51069503,
       0.45789736, 0.65800185, 0.7422845 , 0.07780526, 0.28673066,
       0.01068219, 0.46335869, 0.19484706, 0.70412929, 0.83039206,
       0.84944397, 0.14247262, 0.03006604, 0.51393646, 0.36715929,
       0.22954562, 0.75142857, 0.97649672, 0.30055132, 0.34591451,
       0.77663079, 0.53541247, 0.77120629, 0.89568756, 0.29735281,
       0.99093551, 0.64957015, 0.43128065, 0.11558586, 0.51707

In [32]:
array_1 = np.unique(array_1)
array_2 = np.unique(array_2)
array_3 = np.setdiff1d(array_1, array_2)
array_4 = np.setdiff1d(array_2, array_1)
array_5 = np.intersect1d(array_1, array_2)

In [34]:
print(len(array_1))
print(len(array_2))
print(len(array_3))
print(len(array_4))
print(len(array_5))

80
80
80
80
0
