In [2]:
import numpy as np

In [3]:
#Ejercicio 1: Creamos array
array = np.random.rand(2,3,5)
array =np.round(array, decimals=1)
array

array([[[0.9, 0.5, 0.2, 0.4, 0.6],
        [0.1, 0.5, 0.4, 0.3, 0. ],
        [0.7, 0.2, 0.7, 0.3, 0.7]],

       [[0.1, 0.4, 0.6, 0.7, 0.7],
        [0.5, 0.5, 0.7, 0.9, 0.6],
        [0.5, 0.3, 0.5, 0.7, 0.5]]])

In [4]:
#Ejercicio 2
media_array = np.mean(array)
media_array = np.round(media_array, decimals = 1)
print('La media del array es:', media_array)


La media del array es: 0.5


In [5]:
#Ejercicio 3
max_array = np.max(array)
max_array = np.round(max_array, decimals = 1)
print('El numero máximo del array es:', max_array)

El numero máximo del array es: 0.9


In [6]:
#Ejercicio 4
min_array = np.min(array)
min_array = np.round(min_array, decimals = 1)
print('El numero mínimo del array es:', min_array)

El numero mínimo del array es: 0.0


In [15]:
#Ejercicio 5
array_vacio1 = np.empty((2,3,5))

lista = []

for num in array:
    if np.any(array == media_array):
        lista += 'A'
    elif np.any(array > media_array):
        lista +='B'
    elif np.any(array < media_array):
        lista +='C'
    else:
        lista +='D'
        
print(lista)
        


['A', 'A']


In [44]:

array_vacio = np.where(array_vacio == media_array, 'A', array_vacio)
print(array_vacio)
array_vacio = np.where(array_vacio >= media_array, 'B', array_vacio)
#array_vacio = np.where(array_vacio > media_array, 'C', array_vacio)


[[['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]]


/tmp/ipykernel_22836/197966875.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  array_vacio = np.where(array_vacio == media_array, 'A', array_vacio)


TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'

In [9]:
for cosa in array_vacio:
    if cosa == media_array:
        array_vacio = np.where(array_vacio == media_array, 'A', array_vacio)
    elif cosa > media_array:
        array_vacio = np.where(array_vacio > media_array, 'B', array_vacio)
    elif cosa < media_array:
        array_vacio = np.where(array_vacio < media_array, 'C', array_vacio)

print(array_vacio)

/tmp/ipykernel_22836/2590671831.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if cosa == media_array:


TypeError: '<' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'

In [33]:
array_vacio1 = np.all(['B' if num < media_array else 'C' for num in array_vacio1])
print(array_vacio1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [38]:
prueba_array1 = np.random.randint(1,10,(2,3))
prueba_array1

media_prueba_array1 = np.mean(prueba_array1)
media_prueba_array1

4.833333333333333

In [39]:
prueba_vacio1 = np.empty_like(prueba_array1)

In [43]:
#prueba_array1[prueba_array1 == media_prueba_array1] = 1000
prueba_array1[prueba_array1 <= media_prueba_array1] = 1000
prueba_array1[prueba_array1 >= media_prueba_array1] = 2000
print(prueba_array1)

[[2000 2000 2000]
 [2000 2000 2000]]


In [3]:
matriz = np.random.rand(2,3,5)
matriz =np.round(matriz, decimals=1)

media_matriz = np.mean(matriz)

matriz_vacia = np.empty_like(matriz)
matriz


array([[[0.8, 0.6, 0.5, 0.9, 0.5],
        [0.4, 0. , 0.2, 0.4, 0.8],
        [0.2, 0.2, 0.2, 0.9, 0.3]],

       [[0.4, 0. , 0.9, 0.5, 0.2],
        [0.9, 0.6, 0.4, 0.9, 0.8],
        [0.8, 0.9, 0.9, 0. , 0.2]]])

In [7]:
for bloque in range(len(matriz)):
    for fila in range(len(matriz[bloque])):
        for numero in range(fila):
            if numero == media_matriz:
                num = 1 #A
            if numero < media_matriz:
                num = 2 #B
            if numero > media_matriz:
                num = 3 #C

#matriz_vacia[bloque][fila][numero] = num
matriz_vacia.fill(num)
print(matriz_vacia)

[[[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]


In [ ]:
#Mas pruebas
matriz = np.random.rand(2,3,5)
matriz =np.round(matriz, decimals=1)

media_matriz = np.mean(matriz)
max_array = np.max(matriz)
max_array = np.round(max_array, decimals = 1)
min_array = np.min(matriz)
min_array = np.round(min_array, decimals = 1)

matriz_vacia = np.empty((2,3,5), str)
#matriz_vacia = str(matriz_vacia)
matriz_vacia 

In [ ]:
#Mas pruebas

for bloque in range(len(matriz)):
    for fila in range(len(matriz[bloque])):
        for numero in range(len(matriz[bloque, fila])):
            #print(numero)
            if numero == media_matriz:
                num = 'A'
            if numero < media_matriz:
                num = 'B'
            if numero > media_matriz:
                num = 'C'
            if numero == max_array:
                num = 'D'
            if numero == min_array:
                num = 'E'
            matriz_vacia[bloque][fila][numero] = num
#matriz_vacia.fill(num)
matriz_vacia

In [ ]:
#Mas pruebas
# print(media_matriz)
# print(matriz)
# print(max_array)
# print(min_array)


for bloque in range(len(matriz)):
    for fila in range(len(matriz[bloque])):
        for numero in range(len(matriz[bloque, fila])):
            valor = matriz_vacia[bloque][fila][numero]
            if valor == media_matriz:
                num = 'A'
            if valor < media_matriz:
                num = 'B'
            if valor > media_matriz:
                num = 'C'
            if valor == max_array:
                num = 'D'
            if valor == min_array:
                num = 'E'
            matriz_vacia[bloque][fila][numero] = num
matriz_vacia.fill(num)
matriz_vacia