In [8]:
import numpy as np

#Ejercicio 1
lista1 = [1,2,3,4,5,6,7,8,9,10]
ej1_1 = np.array(lista1)
ej1_1

ej1_2 = np.random.randint(0,100, (2,3))
ej1_2

ej1_3 = np.random.randint(0,100, (2,3,5))
ej1_3

#Ejercicio 2

def propiedades_array(array):
    print(array.ndim)
    print(array.dtype)
    print(array.shape)
    print(array.size)

propiedades_array(ej1_1)
#propiedades_array(ej1_2)

#Ejercicio 3
ej3 = np.eye(3,3)
ej3

#Ejercicio 4
ej4 = np.ones_like(ej1_3)
ej4

#Ejercicio 5
print('Shape ej1_2:',ej1_2.shape)
print('Shape ej3:', ej3.shape)
print('No se pueden sumar porque no tienen la misma forma. Devuelve el siguiente error:')
print('ej1_2 + ej3 = ValueError: operands could not be broadcast together with shapes (2,3) (3,3)') 
print('\n')
matriz_nueva = np.random.randint(0,100, (3,3))
print('Matriz nueva:', '\n',matriz_nueva)
print('Suma de matrices:', '\n', ej3 + matriz_nueva)

ej5_4 = np.multiply(matriz_nueva, ej3)
print('Multiplicación matrices:', '\n', ej5_4)
ej5_5 = np.divide(matriz_nueva, ej3)
print('División matrices:', '\n', ej5_5)


1
int64
(10,)
10
Shape ej1_2: (2, 3)
Shape ej3: (3, 3)
No se pueden sumar porque no tienen la misma forma. Devuelve el siguiente error:
ej1_2 + ej3 = ValueError: operands could not be broadcast together with shapes (2,3) (3,3)


Matriz nueva: 
 [[10  1 77]
 [38 36 14]
 [75 12 59]]
Suma de matrices: 
 [[11.  1. 77.]
 [38. 37. 14.]
 [75. 12. 60.]]
Multiplicación matrices: 
 [[10.  0.  0.]
 [ 0. 36.  0.]
 [ 0.  0. 59.]]
División matrices: 
 [[10. inf inf]
 [inf 36. inf]
 [inf inf 59.]]


/tmp/ipykernel_8941/925118025.py:45: RuntimeWarning: divide by zero encountered in true_divide
  ej5_5 = np.divide(matriz_nueva, ej3)
